### Event Creation (Organizer Only)
POST http://localhost:8800/api/events
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDQ4NDMxZTU3NWM2MDljNjNiYzRkMSIsInJvbGUiOiJPcmdhbmlzYXRldXIiLCJpYXQiOjE3MzI1NjY3NTV9.Aqw4SAr54lVBXR1e3WhHisd-RsJB482eHxCto8-QsD0


{
  "title": "Sample Event Title 2",
  "description": "This is a description of the sample event 2.",
  "location": "123 Sample Street, Sample City",
  "date": "2024-11-31T18:00:00Z",
  "participants": [
    "674637e20c77d673280c453f",
    "674490cf763da06a8902005f"
  ], 
  "maxParticipants": 100
}

### Event Update (Organizer Only)
PUT http://localhost:8800/api/events/674638d44c62b4de423d3ab7
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDc3MDMxNmY2ZGUyNGFjNDU0ZWFhOSIsInJvbGUiOiJQYXJ0aWNpcGFudCIsImlhdCI6MTczMjgzMTM5N30.8Y4VMOqZ30f_htEeNPLOdgVHJNQWDxJZONCG_m2JdiQ


{
  
  "participants": [
    "67463c66b7233f8ef46f3128"
  ], 
  "maxParticipants": 150
}

### Get All Events
GET  http://localhost:8800/api/events
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDQ4NDMxZTU3NWM2MDljNjNiYzRkMSIsInJvbGUiOiJPcmdhbmlzYXRldXIiLCJpYXQiOjE3MzI1NjY3NTV9.Aqw4SAr54lVBXR1e3WhHisd-RsJB482eHxCto8-QsD0


### Get Single Event
GET  http://localhost:8800/api/events/user-events
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDc3MDMxNmY2ZGUyNGFjNDU0ZWFhOSIsInJvbGUiOiJQYXJ0aWNpcGFudCIsImlhdCI6MTczMjgzMTk3MH0.R_lYfZpliOT69rC4Ey0Iv83uDaDZYTA8c0pbTVNDbps

### Event Update (Organizer Only)
PUT  http://localhost:8800/api/events/6744e04918bd699001fe9241
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDQ4NDMxZTU3NWM2MDljNjNiYzRkMSIsInJvbGUiOiJPcmdhbmlzYXRldXIiLCJpYXQiOjE3MzI1NjY3NTV9.Aqw4SAr54lVBXR1e3WhHisd-RsJB482eHxCto8-QsD0


{
  "title": "Sample Event Title."
}

### Delete Event (Organizer Only)
DELETE http://localhost:8800/api/events/6744e04918bd699001fe9241
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDQ4NDMxZTU3NWM2MDljNjNiYzRkMSIsInJvbGUiOiJPcmdhbmlzYXRldXIiLCJpYXQiOjE3MzI1NDY1NTV9.pBNFn1_nztvewFgp3kXfrSEyT1poFGraqNyVsq4sNlM

### GENERATE PDF
GET  http://localhost:8800/api/events/pdf
Content-Type: : application/pdf
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDQ4NDMxZTU3NWM2MDljNjNiYzRkMSIsInJvbGUiOiJPcmdhbmlzYXRldXIiLCJpYXQiOjE3MzI1NDY1NTV9.pBNFn1_nztvewFgp3kXfrSEyT1poFGraqNyVsq4sNlM

