### User Registration
POST http://localhost:8800/api/auth/register
Content-Type: application/json

{
  "fullName": "Parody clara",
  "email": "iparodt@gmail.com",
  "password": "StrongP@ssw0rd123!"
}

### User Login
POST http://localhost:8800/api/auth/login
Content-Type: application/json

{
  "email": "john@gmail.com",
  "password": "StrongP@ssw0rd123!"
}

### Update User (Requires Authentication Token)
PUT http://localhost:8800/api/auth/user/674490cf763da06a8902005f
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDQ4NDMxZTU3NWM2MDljNjNiYzRkMSIsInJvbGUiOiJPcmdhbmlzYXRldXIiLCJpYXQiOjE3MzI1NDkxNDJ9.Hcr2ZL_DYuuAMPw8IhwHDpiFRL0vApCKACC9_llGqtU

{
  "fullName": "John Doe"
}

### Get All Users (Organizer Only)
GET http://localhost:8800/api/auth/users
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDQ4NDMxZTU3NWM2MDljNjNiYzRkMSIsInJvbGUiOiJPcmdhbmlzYXRldXIiLCJpYXQiOjE3MzI1NDkxNDJ9.Hcr2ZL_DYuuAMPw8IhwHDpiFRL0vApCKACC9_llGqtU

### Get User by ID (Organizer Only)
GET http://localhost:8800/api/auth/user/674490cf763da06a8902005f
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDQ4NDMxZTU3NWM2MDljNjNiYzRkMSIsInJvbGUiOiJPcmdhbmlzYXRldXIiLCJpYXQiOjE3MzI1NDY1NTV9.pBNFn1_nztvewFgp3kXfrSEyT1poFGraqNyVsq4sNlM

### Delete User (Organizer Only)
DELETE http://localhost:8800/api/auth/user/67448487e575c609c63bc4d4
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDQ4NDMxZTU3NWM2MDljNjNiYzRkMSIsInJvbGUiOiJPcmdhbmlzYXRldXIiLCJpYXQiOjE3MzI1NDY1NTV9.pBNFn1_nztvewFgp3kXfrSEyT1poFGraqNyVsq4sNlM

### Logout
POST http://localhost:8800/api/auth/logout/67448431e575c609c63bc4d1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDQ4NDMxZTU3NWM2MDljNjNiYzRkMSIsInJvbGUiOiJPcmdhbmlzYXRldXIiLCJpYXQiOjE3MzI1NDY1NTV9.pBNFn1_nztvewFgp3kXfrSEyT1poFGraqNyVsq4sNlM